/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// 37. peripheral clock configuration
// before using peripheral, setup clock first.
// macro def.
#define ADC1_BASE_ADDR  0x50000000UL
#define ADC1_CR_REG_OFFSET 0x08UL
#define ADC1_CR_REG_ADDR (ADC1_BASE_ADDR + ADC1_CR_REG_OFFSET)

#define RCC_BASE_ADDR 0x40021000UL
#define AHB_ENR_OFFSET 0x14UL
#define RCC_AHB_ENR_ADDR (RCC_BASE_ADDR + AHB_ENR_OFFSET)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t* pAdc1CrReg = (uint32_t*)  ADC1_CR_REG_ADDR;
	uint32_t* pRccAhbEnr = (uint32_t*)  RCC_AHB_ENR_ADDR;
	// 1. Enable the peripheral clock for ADC1
	// without this, the ADC_CR reg. modify won't enable.
	*pRccAhbEnr |= (1<<28);
	// 2. modify the ADC1 CR register
	*pAdc1CrReg |= (1 << 0);
    /* Loop forever */
	for(;;);
}
