/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// Setup HSE clock and measure its speed using GPIOA

#include <stdint.h>


#define RCC_BASE_ADDR 					0x40021000UL
#define RCC_CFGR_OFFSET 				0x04UL
#define RCC_CFGR_REG_ADDR 				(RCC_BASE_ADDR + RCC_CFGR_OFFSET)
#define RCC_AHB_ENR_OFFSET				0x14UL
#define RCC_AHB_ENR_ADDR				(RCC_BASE_ADDR + RCC_AHB_ENR_OFFSET)
#define RCC_CR_OFFSET					0x00
#define RCC_CR_ADDR						(RCC_BASE_ADDR + RCC_CR_OFFSET)

#define GPIOA_BASE_ADDR 				0x48000000UL
#define GPIOA_MODER_ADDR				(GPIOA_BASE_ADDR + 0x00)
#define GPIOA_AFRH_OFFSET				0x24UL
#define GPIOA_AFRH_ADDR					(GPIOA_BASE_ADDR + GPIOA_AFRH_OFFSET)
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t* pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
	uint32_t* pRccCrReg = (uint32_t*) RCC_CR_ADDR;
	/* individual part for HSE clock */
	//1. Enable the HSE clock using HSEON bit (RCC_CR)
	*pRccCrReg |= (1 << 16);

	//2. Wait until HSE clock from the external crystal stabilizes (only if crystal is connected )
	while( !( (*pRccCrReg) & (1 << 17) ) );

	//3. Switch the system clock to HSE (RCC_CFGR)
	*pRccCfgrReg |= (1 << 0);
	*pRccCfgrReg &= ~(1 << 1);

	/* same setting as HSI configuration */
	//1. Configure the RCC_CFGR MCO bit fields to select HSE as clock source
	*pRccCfgrReg |= (0b110 << 24);

	//Configure MCO prescaler (not enable in STM32F3discovery, not support)
	*pRccCfgrReg |= (0b010 << 28);

	//2. Configure PA8 to AF0 mode to behave as MCO signal

	//a ) Enable the peripheral clock (AHB2) for GPIOA peripheral
	uint32_t* pRccCfgrEnr = (uint32_t*) RCC_AHB_ENR_ADDR;
	*pRccCfgrEnr |= (1 << 17);//Enable GPIOA peripheral clock

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode
	uint32_t* pGPIOAModeReg = (uint32_t*) GPIOA_MODER_ADDR;
	*pGPIOAModeReg |= (1 << 17);
	*pGPIOAModeReg &= ~(1 << 16);

	//c ) Configure the alternation function register to set the mode 0 for PA8
	uint32_t* pGPIOAAltFunHighReg = (uint32_t*) GPIOA_AFRH_ADDR;
	*pGPIOAAltFunHighReg &= ~(0b1111 << 0);

    /* Loop forever */
	for(;;);
}
